// MIT License
//
// Copyright (c) 2020, The Regents of the University of California,
// through Lawrence Berkeley National Laboratory (subject to receipt of any
// required approvals from the U.S. Dept. of Energy).  All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

//
//  This file was auto-generated by CMake. DO NOT EDIT!
//

/** \def TIMEMORY_VERSION
 * \brief
 *  MAJOR_VERSION: TIMEMORY_VERSION / 10000
 *  MINOR_VERSION: TIMEMORY_VERSION % 10000 / 100
 *  PATCH_VERSION: TIMEMORY_VERSION % 100
 */

#define TIMEMORY_VERSION_MAJOR 3
#define TIMEMORY_VERSION_MINOR 2
#define TIMEMORY_VERSION_PATCH 0

#define TIMEMORY_VERSION 30200
#define TIMEMORY_VERSION_STRING "3.2.0.dev4"

#define TIMEMORY_GIT_DESCRIBE "v3.1.0-168-g2d1eddd8"
#define TIMEMORY_GIT_REVISION "2d1eddd843e0fcb8c84507a11de12f75fbc3bfb9"
